### ISSUE TITLE
Some Missing ADFs for examples and example variants

### ISSUE THREAD

**Issue by mithrendal** [alpine9000/amiga_examples#1]
Hi @alpine9000 
first I want to thank you for this collection of amiga examples. It does cover a lot of hardware programming aspects. Yours example collection is therefore currently used as test programs for a new amiga emulator called [vAmiga](https://github.com/dirkwhoffmann/vAmiga). That is an Amiga-Emulator made specific for macOS. We want to get it pass every of yours example. Fortunately most of yours examples are already compiled/assemled and packed into an ADF. So we can visually compare with SAE. But for certain tests there is no ADF at all or there are variants and only one variant is in the ADF.

Here is an overview about what of your examples is already mastered by vAmiga
dirkwhoffmann/vAmiga#35

In order to help dirkwhoffmann I tried to get some of the missing ADFs build. But I run into difficulties. Especially the imagecon program  gave me hard times, lots of makefile errors. 

Maybe you are still around and maybe vAmiga does made you curious and also interests you and you maybe also don't mind to post the imagecon tool as a binary for macOS under yours github release section ? Or you could just drag it into this issue ?  

Especially we do like to get your example#10 the blitspeed example running. With it we can tune the blitter to get the exact speeds.
Here is the issue to get it run: dirkwhoffmann/vAmiga#38

Do you maybe still have the ADFs with the Variants 1 - 5 Bitplanes somewhere on your hardrive? 

Again thank you for this great repository ! Amiga rulez. 😜

**Comment by alpine9000** [comment]
I checked out a fresh version of the repo and got it building. (note: the tools build fine using clang on OSX, so no need to install gcc).

I also included most of the missing ADF files as well as the ADFs for each of the 2,4,8,16 and 32 color modes in the blit speed example.

I wouldnt bother with the 028.bs example as that was just the beginnings of the Blocky Skies game.

**Comment by mithrendal** [comment]
Hi alpine9000,
again thank you very much that you helped us out 😃.
all the best 
❤️

**Comment by dirkwhoffmann** [comment]
Many thanks from my side, too!!!
